#!/bin/bash
# Quick Railway deployment checklist

echo "🚂 Railway Deployment Checklist"
echo ""
echo "✓ Railway configuration updated (railway.json)"
echo "✓ AWS files removed"
echo ""
echo "📋 Next steps:"
echo ""
echo "1. Make sure code is committed to GitHub:"
echo "   git add ."
echo "   git commit -m 'Ready for Railway deployment'"
echo "   git push"
echo ""
echo "2. Go to https://railway.app"
echo "   - Login with GitHub"
echo "   - New Project → Deploy from GitHub"
echo "   - Select: self-learning-ai-backend"
echo ""
echo "3. Add environment variables in Railway (from your .env file):"
echo "   GROQ_API_KEY=<your_key>"
echo "   SUPABASE_URL=<your_url>"
echo "   SUPABASE_KEY=<your_key>"
echo "   PORT=5000"
echo ""
echo "4. Click Deploy and wait 2-3 minutes"
echo ""
echo "5. Get your URL from Settings → Generate Domain"
echo ""
echo "📖 Full guide: RAILWAY_DEPLOY.md"
